export const stringsMap = {
  en: {
    homeTitle: 'Local Events',
    searchPlaceholder: 'Search keyword or city',
    profile: 'Profile',
    addFav: 'Add to Favourites',
    removeFav: 'Remove Favourite',
    keyword: 'Keyword',
    city: 'City',
    search: 'Search',
    about: 'About',
    noInfo: 'No additional information available.',
    noEvents: 'No events — try searching',
    loading: 'Loading...',
    noFavYet: 'No favourites yet.',
    dummyUser: 'User: Demo User (mock)',
    favourites: 'Favourites',
    appName: 'City Pulse',
    appDesc: 'Local Events Explorer',
    convert: 'Convert',
  },
  ar: {
    homeTitle: 'الأحداث المحلية',
    searchPlaceholder: 'ابحث اسم المدينة أو الحدث',
    profile: 'الملف الشخصي',
    addFav: 'إضافة إلى المفضلة',
    removeFav: 'إزالة من المفضلة',
    keyword: 'الكلمة المفتاحية',
    city: 'المدينة',
    search: 'بحث',
    about: 'حول التطبيق',
    noInfo: 'لا توجد معلومات إضافية متاحة.',
    noEvents: 'لا توجد فعاليات — جرّب البحث',
    loading: 'جارٍ التحميل...',
    noFavYet: 'لا توجد عناصر في المفضلة بعد.',
    dummyUser: 'المستخدم: مستخدم تجريبي (وهمي)',
    favourites: 'المفضلة',
    appName: 'نبض المدينة',
    appDesc: 'مستكشف الفعاليات المحلية',
    convert: 'يتحول',
  },
};
